# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 553088d9ee655d1fb755a72c8c0d5674723a13d171c60447414c62300afc4fd274f05237d89d992313e8fe1e2367e566ca063c5eaa5d991f958fff82dbc2f84c

test:
  secret_key_base: 3c112a80ace54d193069865a6f8bac25be54409516764ae55ae2c7d1c70ac35d1fb4fc3539fb8dd4b871ae7e5b41583e2115e6f9d949826dd75b272f239a72f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
